packages:
  - back-end
  - back-end/apps/*
  - back-end/typeorm
  - front-end
  - automation

catalog:
  '@hiero-ledger/proto': 2.28.0
  '@hiero-ledger/sdk': 2.82.0
  '@types/bcrypt': 6.0.0
  '@types/jest': 30.0.0
  '@types/node': 25.5.0
  '@types/semver': 7.7.1
  argon2: 0.44.0
  axios: 1.15.2
  bcrypt: 6.0.0
  bcryptjs: 3.0.3
  dotenv: 17.4.2
  jest: 30.3.0
  jszip: 3.10.1
  long: 5.3.2
  pg: 8.20.0
  prettier: 3.8.3
  reflect-metadata: 0.2.2
  semver: 7.7.4
  ts-jest: 29.4.6
  ts-loader: 9.5.7
  ts-node: 10.9.2
  typeorm: 0.3.28
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - bcrypt
  - better-sqlite3
  - cpu-features
  - electron
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sqlite3
  - ssh2
  - unrs-resolver
  - vue-demi
