# For dev use only, not for production deployments.
{{- if not .Values.stackgres.enabled }}
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ include "transactiontool.fullname" . }}-dev
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '5Gi'
{{- end -}}
