{{- if and .Values.stackgres.enabled (hasKey .Values.stackgres.shardedCluster.coordinator.managedSql "scripts") }}
{{- range .Values.stackgres.shardedCluster.coordinator.managedSql.scripts }}
{{- $scriptName := .sgScript }}
{{- if hasKey $.Values.stackgres.script.coordinator $scriptName }}
---
apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: {{ $scriptName }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- index $.Values.stackgres.script.coordinator $scriptName | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}
