import listenForKeyPairEvents from './keyPairs';
import listenForLocalUserEvents from './localUser';
import listenForAccountsEvents from './accounts';
import listenForTransactionsEvents from './transactions';
import listenForFilesEvents from './files';
import listenForTransactionDraftsEvents from './transactionDrafts';
import listenForTransactionGroupsEvents from './transactionGroups';
import listenForComplexKeyEvents from './complexKeys';
import listenForOrganizationEvents from './organizations';
import listenForOrganizationCredentialsEvents from './organizationCredentials';
import listenForContactEvents from './contacts';
import listenForPublicKeyLinkedEvents from './publicKeyLinked';
import listenForEncryptedKeysEvents from './encryptedKeys';
import listenForClaimEvents from './claim';
import listenForSafeStorageEvents from './safeStorage';
import listenForDataMigrationEvents from './dataMigration';
import listenForSDKEvents from './sdk';

export default () => {
  listenForKeyPairEvents();
  listenForLocalUserEvents();
  listenForAccountsEvents();
  listenForTransactionsEvents();
  listenForFilesEvents();
  listenForTransactionDraftsEvents();
  listenForTransactionGroupsEvents();
  listenForComplexKeyEvents();
  listenForOrganizationEvents();
  listenForOrganizationCredentialsEvents();
  listenForContactEvents();
  listenForPublicKeyLinkedEvents();
  listenForEncryptedKeysEvents();
  listenForClaimEvents();
  listenForSafeStorageEvents();
  listenForDataMigrationEvents();
  listenForSDKEvents();
};
