apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: gcr.io/transaction-tool-dev/notifications
        name: notifications
        env:
          - name: RABBITMQ_URI
            value: 'amqp://rabbitmq:5672'
          - name: BREVO_USERNAME
            valueFrom:
              secretKeyRef:
                name: brevo
                key: username
          - name: BREVO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: brevo
                key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
    - name: '3020'
      port: 3020
      protocol: TCP
      targetPort: 3020
  selector:
    app: notifications
  type: ClusterIP