---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: hedera-transaction-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: gcr.io/transaction-tool-dev/notifications
          env:
            - name: HTTP_PORT
              value: '3020'
            - name: AUTH_HOST
              value: '3001'
            - name: AUTH_PORT
              value: '3001'
            - name: RABBITMQ_USERNAME
              value: 'tool-back-end'
            - name: RABBITMQ_PASSWORD
              value: 'plainpass'
            - name: RABBITMQ_URI
              value: 'amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq:5672'
            - name: BREVO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: brevo-secret
                  key: username
            - name: BREVO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brevo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: hedera-transaction-tool
spec:
  ports:
    - name: 'http'
      port: 3020
      protocol: TCP
      targetPort: 3020
  selector:
    app: notifications
  type: NodePort