apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: notsureyet/notifications/production
        name: notifications
        env:
          - name: TCP_PORT
            value: '3020'
        ports:
          - containerPort: 3020
