### Create user local
POST http://localhost:3001/auth/signup
content-type: application/json

{
  "email": "john.bair+16@swirldslabs.com"
}

### Log in local
POST http://localhost:3001/auth/login
content-type: application/json

{
  "email": "john.bair+16@swirldslabs.com",
  "password": "1234567890"
}

### Log in remote
POST https://hederatransactiontool.com/auth/login
content-type: application/json

{
  "email": "john.bair@swirldslabs.com",
  "password": "123456789"
}

### Log in Ted
POST http://localhost:3001/auth/login
content-type: application/json

{
  "email": "pisosoft@outlook.com",
  "password": "NIbl1iIMJcZVEMz5"
}

### Sing out
POST http://localhost:3000/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obkB0ZXN0LmNvbSIsImlhdCI6MTcxMDc3NDAzNywiZXhwIjoxNzEwODEwMDM3fQ.h_NwgTMmancbf-ifAlOtH9SuGGqf6MW4COjbryIp14s

### Update password for current user
PATCH https://hederatransactiontool.com/auth/change-password
content-type: application/json

{
  "oldPassword": "123456789",
  "newPassword": "1234567890"
}

### Reset password
POST http://localhost:3001/auth/reset-password
content-type: application/json

{
  "email": "john.ted@thing.com"
}