---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chain
  name: chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain
  template:
    metadata:
      labels:
        app: chain
    spec:
      containers:
      - image: gcr.io/transaction-tool-dev/chain
        name: chain
        env:
          - name: RABBITMQ_URI
            value: 'amqp://rabbitmq:5672'
          - name: POSTGRES_HOST
            value: 'postgres'
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_DATABASE
            value: 'postgres'
          - name: POSTGRES_USERNAME
            value: 'postgres'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_SYNCHRONIZE
            value: 'false'
---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: notifications
#  name: notifications
#spec:
#  ports:
#    - name: '3020'
#      port: 3020
#      protocol: TCP
#      targetPort: 3020
#  selector:
#    app: notifications
#  type: ClusterIP