apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: api
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
