apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.namespace }}
  {{- if and (hasKey .Values.api.service "ingress") (hasKey .Values.api.service.ingress "annotations") (not (empty .Values.api.service.ingress.annotations)) }}
  annotations:
    {{- toYaml .Values.api.service.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: api
  ports:
    - name: 'http'
      port: {{ .Values.api.service.httpPort }}
      protocol: TCP
      targetPort: {{ .Values.api.service.targetPort }}
  type: NodePort
