apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api
  ports:
    - name: 'tcp'
      port: {{ .Values.auth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.auth.service.targetPort }}
  type: {{ .Values.auth.service.type }}