apiVersion: v1
kind: Service
metadata:
  name: {{ include "transactiontool.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.annotations }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - name: 'tcp'
      port: {{ .Values.auth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.auth.service.targetPort }}
  type: ClusterIP
