apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-tool.fullname" . }}-auth
  namespace: {{ .Release.namespace }}
  annotations: {{ include "common.annotations" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - name: 'tcp'
      port: {{ .Values.auth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.auth.service.targetPort }}
  type: ClusterIP
