apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transactiontool.fullname" . }}-chain
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "common.annotations" . | nindent 4 }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.chain.replicas }}
  selector:
    matchLabels:
      app: chain
  template:
    metadata:
      annotations: {{ include "common.annotations" . | nindent 8 }}
      labels:
        app: chain
        {{ include "common.labels" . | nindent 8 }}
    spec:
      containers:
        - name: chain
          image: gcr.io/transaction-tool-dev/chain
          resources:
            requests:
              memory: {{ .Values.chain.resources.requests.memory | quote }}
              cpu: {{ .Values.chain.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.chain.resources.limits.memory | quote }}
              cpu: {{ .Values.chain.resources.limits.cpu | quote }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ dig "cluster" "config" "secretBackend" "externalSecret" "name" .Values.rabbitmq.secretName .Values.rabbitmq }}
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ dig "cluster" "config" "secretBackend" "externalSecret" "name" .Values.rabbitmq.secretName .Values.rabbitmq }}
                  key: password
            - name: RABBITMQ_URI
              value: {{ if not (empty .Values.rabbitmq.endpoint) -}}
                'amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ .Values.rabbitmq.endpoint }}:{{ .Values.rabbitmq.port }}'
              {{- else -}}
                'amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@{{ template "transactiontool.fullname" . }}-rmq.{{ .Release.Namespace}}.svc:{{ .Values.rabbitmq.port }}'
              {{- end }}
            - name: POSTGRES_HOST
              value: {{ include "transactiontool.sqlHost" . }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | squote }}
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.postgres.secretName (printf "postgres-%s" .Release.Namespace) }}
                  key: database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.postgres.secretName (printf "postgres-%s" .Release.Namespace) }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ coalesce .Values.postgres.secretName (printf "postgres-%s" .Release.Namespace) }}
                  key: password
            - name: POSTGRES_SYNCHRONIZE
              value: {{ .Values.chain.env.POSTGRES_SYNCHRONIZE | squote }}
            - name: POSTGRES_MAX_POOL_SIZE
              value: {{ .Values.chain.env.POSTGRES_MAX_POOL_SIZE | squote }}
            - name: REDIS_URL
              value: {{ include "transactiontool.redisUrl" .  }}
