apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "transaction-tool.fullname" . }}-back-end
  namespace: {{ .Release.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{ include "common.annotations" . | nindent 4 }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: notifications
                port:
                  number: {{ .Values.notifications.service.httpPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.service.httpPort }}
