apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: {{ .Release.Namespace }}
  {{- if and (hasKey .Values.notifications.service "ingress") (hasKey .Values.notifications.service.ingress "annotations") (not (empty .Values.notifications.service.ingress.annotations)) }}
  annotations:
    {{- toYaml .Values.notifications.service.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: 'http'
      port: {{ .Values.notifications.service.httpPort }}
      protocol: TCP
      targetPort: {{ .Values.notifications.service.targetPort }}
  selector:
    app: notifications
  type: NodePort
