apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: 'http'
      port: 3020
      protocol: TCP
      targetPort: 3020
  selector:
    app: notifications
  type: NodePort
