{{- if hasKey .Values.postgres.cluster "config" }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "transactiontool.fullname" . }}-pg
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "common.annotations" . | nindent 4 }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
{{- .Values.postgres.cluster.config | toYaml | nindent 2 }}
{{- end }}
