{{- if hasKey .Values.rabbitmq.cluster "config" }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "transactiontool.fullname" . }}-rmq
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "common.annotations" . | nindent 4 }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
{{- .Values.rabbitmq.cluster.config | toYaml | nindent 2 }}
{{- end }}
