{{- if .Values.rabbitmq.enabled }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "transactiontool.fullname" . }}-rmq
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.annotations }}
  annotations:  {{- toYaml .Values.global.annotations | nindent 4 }}
{{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
{{- .Values.rabbitmq.cluster.config | toYaml | nindent 2 }}
{{- end }}
