steps:
  # API service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/transaction-tool-dev/api',
        '-f',
        'apps/api/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/transaction-tool-dev/api']
  # Chain service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/transaction-tool-dev/chain',
        '-f',
        'apps/chain/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/transaction-tool-dev/chain']
  # Notifications service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/transaction-tool-dev/notifications',
        '-f',
        'apps/notifications/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/transaction-tool-dev/notifications']
