steps:
  # API service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-south1-docker.pkg.dev/transaction-tool-dev/api/development',
        '-f',
        'apps/api/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-south1-docker.pkg.dev/transaction-tool-dev/api/development']
  # Chain service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-south1-docker.pkg.dev/transaction-tool-dev/chain/development',
        '-f',
        'apps/chain/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-south1-docker.pkg.dev/transaction-tool-dev/chain/development']
  # Notifications service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-south1-docker.pkg.dev/transaction-tool-dev/notifications/development',
        '-f',
        'apps/notifications/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-south1-docker.pkg.dev/transaction-tool-dev/notifications/development']
