services:
  api:
    volumes:
      - .:/usr/src/app/back-end

  chain:
    volumes:
      - .:/usr/src/app/back-end

  notifications:
    volumes:
      - .:/usr/src/app/back-end

  database:
    volumes:
      - ./pgdata:/var/lib/postgresql
