packages:
  - apps/*
  - typeorm

catalog:
  ts-node: 10.9.2
  typescript: 5.7.3
  typeorm: 0.3.20
  pg: 8.13.1
  reflect-metadata: 0.2.2
  '@types/jest': 29.5.14
  jest: 29.7.0
  ts-jest: 29.2.5

onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
  - cpu-features
  - protobufjs
  - sqlite3
  - ssh2
