packages:
  - apps/*
  - typeorm

catalog:
  typeorm: 0.3.20
  pg: 8.13.1
  reflect-metadata: 0.2.2

onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
  - cpu-features
  - protobufjs
  - sqlite3
  - ssh2
