packages:
  - apps/*
  - typeorm

catalog:
  ts-node: 10.9.2
  typescript: 5.9.3
  typeorm: 0.3.28
  pg: 8.20.0
  reflect-metadata: 0.2.2
  '@types/jest': 30.0.0
  jest: 30.3.0
  ts-jest: 29.4.6

onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
  - cpu-features
  - protobufjs
  - sqlite3
  - ssh2
