---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: hedera-transaction-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/transaction-tool-dev/api
          env:
            - name: HTTP_PORT
              value: '3000'
            - name: TCP_PORT
              value: '3001'
            - name: RABBITMQ_USERNAME
              value: 'tool-back-end'
            - name: RABBITMQ_PASSWORD
              value: 'plainpass'
            - name: RABBITMQ_URI
              value: 'amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq:5672'
            - name: POSTGRES_HOST
              value: 'postgres-service'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_SYNCHRONIZE
              value: 'false'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: key
            - name: JWT_EXPIRATION
              value: '365'
            - name: OTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: otp-secret
                  key: key
            - name: OTP_EXPIRATION
              value: '20'
            - name: HEDERA_NETWORK
              value: 'testnet'
            - name: REDIS_URL
              value: 'redis://redis-master:6379'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: hedera-transaction-tool
spec:
  selector:
    app: api
  ports:
    - name: 'tcp'
      port: 3001
      protocol: TCP
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: hedera-transaction-tool
spec:
  selector:
    app: api
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
