name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y build-essential python3.10
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: run hedera local
        run: npx @hashgraph/hedera-local start -d

      - name: Install pnpm
        run: npm i -g pnpm node-gyp @hashgraph/hedera-local

      # - name: prep hedera
      #   uses: actions/checkout@v4
      #   with:
      #     repository: hashgraph/hedera-local-node
      #     path: hedera-local-node
      # - name: run hedera
      #   run: |
      #     npm i
      #     npm run start -- -d
      #   working-directory: hedera-local-node

      - name: Install dependencies
        run: npm install
        working-directory: front-end

      - name: list npm packages
        run: |
          npm ls
        working-directory: front-end

      # - name: Install protobuf
      #   run: pnpm install @hashgraph/proto
      #   working-directory: front-end

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Build
        run: npm run build
        working-directory: front-end

      - name: Build Linux
        run: npm run build:linux
        working-directory: front-end

      - name: Copy example.env files
        run: find apps -type f -name "example.env" -print -exec sh -c 'cp "$1" "$(dirname "$1")/.env"' _ {} \;
        working-directory: back-end

      - name: Install automation dependencies
        run: pnpm install
        working-directory: automation

      - name: run back-end
        run: docker compose up -d
        working-directory: back-end

      - name: run automation
        env:
          EXECUTABLE_PATH: ../front-end/release/linux-unpacked/hedera-transaction-tool
          PRIVATE_KEY: "0x7f109a9e3b0d8ecfba9cc23a3614433ce0fa7ddcc80f2a8f10b222179a5a80d6"
          ENVIRONMENT: LOCALNET

        run: xvfb-run -a pnpm run test
        working-directory: automation

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
