---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain
  namespace: hedera-transaction-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain
  template:
    metadata:
      labels:
        app: chain
    spec:
      containers:
        - name: chain
          image: gcr.io/transaction-tool-dev/chain
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_URI
              value: 'amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq:5672'
            - name: POSTGRES_HOST
              value: 'postgres-service'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_SYNCHRONIZE
              value: 'false'
            - name: REDIS_URL
              value: 'redis://redis-master:6379'
