apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: hedera-transaction-tool
spec:
  replicas: 1
  rabbitmq:
    env:
      - name: RABBITMQ_USERNAME
        valueFrom:
          secretKeyRef:
            name: rabbitmq-credentials
            key: username
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rabbitmq-credentials
            key: password
    additionalConfig: |
      default_user = $(RABBITMQ_USERNAME)
      default_pass = $(RABBITMQ_PASSWORD)